### ISSUE TITLE
Generate Camel Case from underscore style names

### ISSUE THREAD

**Issue by klevis** [joelittlejohn/jsonschema2pojo#848]
Currently if a json has names like **ISO_ALPHA_CD** it will converted into **iSOALPHACD** which it doesn't look good.

It will be nice to be able to understand words from **ISO_ALPHA_CD** and from there construct camel case like **isoAlphaCd**. 
The code below could be changed to not remove certain delimiters which can be configured in property like "**propertyCamelCaseDelimeters**". Than at camelCaseMethod we split by the first delimiter that works and transform to camel case each of the word splited names.
What do you think? Maybe this could currently possible as I am not quite familiar with library yet.

```java
  public String normalizeName(String name) {
        name = capitalizeTrailingWords(name);

        if (isDigit(name.charAt(0))) {
            name = "_" + name;
        }

        return name;
    }
public String capitalizeTrailingWords(String name) {
        char[] wordDelimiters = generationConfig.getPropertyWordDelimiters();

        if (containsAny(name, wordDelimiters)) {
            String capitalizedNodeName = WordUtils.capitalize(name, wordDelimiters);
            name = name.charAt(0) + capitalizedNodeName.substring(1);

            for (char c : wordDelimiters) {
                name = remove(name, c);
            }
        }

        return name;
    }
```

**Comment by joelittlejohn** [comment]
The java name here should be `isoAlphaCd` (if you are using the default propertyWordDelimiters, which includes underscore). I'm actually surprised the naming code doesn't do this already. We should fix this I think.

**Comment by klevis** [comment]
Even with default propertyWordDelimiters the issue is still there. I can send PR since locally I already fixed the issue.

**Comment by joelittlejohn** [comment]
Sure please do. I think this is just a case of replacing `WordUtils.capitalize` with `WordUtils.capitalizeFully`, right?

**Comment by klevis** [comment]
Nice the change you suggested works just fine although originally I worked a bit more than that but .
Already created a pull request.

**Comment by klevis** [comment]
The changed looked easy so I was a bit hasty to push but now I see that some tests are failing therefore I have to check...

**Comment by klevis** [comment]
So I looked at the tests and it seems like we have following failures:

- byDefaultOnlyfirstExtensionRemoved
It assumes that **nameWithExtension.schema** will be trainsformed to **nameWithExtensionSchema** but unfortunately this is not compatible with the change since WordUtils.capitalizeFully will consider the name before '.' as word so it will lower the case of all characters to follow camel case rule.
- propertyNamesAreLowerCamelCase
The same applies here for _PropertyThreeWithSpace.  Just for the first letter '_' defines the word on the right so WordUtils.capitalizeFully lowers the case of the words letters beside the first character of course.

From the tests it looks like it is assumed that default behavior is like described above so maybe we can introduce a new Boolean configuration   like fullCamelCase... or something which it switches between WordUtils.capitalize and WordUtils.capitalizeFully. So we leave the current behavior untouched.

**Comment by joelittlejohn** [comment]
Hmm. How would this work: use `WordUtils.capitalizeFully` _only_ when the string contains zero lowercase chars.

**Comment by klevis** [comment]
Thanks for the suggestion now all the tests are passing and I also added another  IT to cover the new case.

**Comment by klevis** [comment]
@joelittlejohn What about the case when the name is all upper case but without delimiters? 
Right now **DESCRIPTION** will be transformed to **dESCRIPTION** and in my opinion it should be converted to just **description** instead. The change is easy just let me know if you find this also useful to fix.

**Comment by klevis** [comment]
Changes Merged #850.
